image: docker:latest
services:
  - docker:dind
stages:
  - build
build:
  stage: build
  tags:
    - runner
  script:
    - set -euo pipefail
    - NAME="$CI_REGISTRY_IMAGE:$(echo $CI_BUILD_REF|cut -c1-8)"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $NAME .
    - docker push $NAME
    - docker tag $NAME $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - if [ $CI_COMMIT_REF_NAME = "master" ]; then docker tag $NAME $CI_REGISTRY_IMAGE:latest && docker push $CI_REGISTRY_IMAGE:latest; fi
    - if [ "$CI_COMMIT_TAG" ]; then docker tag $NAME $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG && docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG; fi
